import sdk from "@farcaster/frame-sdk";

const APP_URL = "https://farcaster.xyz/miniapps/MiAspAXiw6cZ/claim";

export const SHARE_COPY = {
  postClaim: (amount: string) => 
    `Just claimed ${amount} in fees with Claim \u2728\nIf you've launched tokens, you might have fees waiting.`,
  
  generic: () => 
    `If you've launched tokens on clanker, you probably have unclaimed fees waiting\n\n$CLAIM the fees generated by your tokens \u2014 one click.`,
} as const;

export const MODAL_COPY = {
  successTitle: "Fees Claimed!",
  successDescription: (rewards: string) => `You successfully claimed ${rewards}`,
  shareButton: "SHARE",
  viewTxButton: "View Transaction",
  doneButton: "Done",
} as const;

export function buildPostClaimMessage(amount: string): string {
  return `${SHARE_COPY.postClaim(amount)}\n\nClaim now: ${APP_URL}`;
}

export function buildGenericShareMessage(): string {
  return `${SHARE_COPY.generic()}\n\nClaim now: ${APP_URL}`;
}

export async function shareOnFarcaster(message: string): Promise<boolean> {
  try {
    const result = await sdk.actions.composeCast({
      text: message,
      embeds: [APP_URL],
    });
    
    return result?.cast !== null;
  } catch (error) {
    console.error("[SHARE] Failed to open cast composer:", error);
    return false;
  }
}

export async function sharePostClaim(amount: string): Promise<boolean> {
  const message = buildPostClaimMessage(amount);
  return shareOnFarcaster(message);
}

export async function shareGeneric(): Promise<boolean> {
  const message = buildGenericShareMessage();
  return shareOnFarcaster(message);
}
